export const browserCoreExamples = [
  "synthios browser status",
  "synthios browser start",
  "synthios browser stop",
  "synthios browser tabs",
  "synthios browser open https://example.com",
  "synthios browser focus abcd1234",
  "synthios browser close abcd1234",
  "synthios browser screenshot",
  "synthios browser screenshot --full-page",
  "synthios browser screenshot --ref 12",
  "synthios browser snapshot",
  "synthios browser snapshot --format aria --limit 200",
  "synthios browser snapshot --efficient",
  "synthios browser snapshot --labels",
];

export const browserActionExamples = [
  "synthios browser navigate https://example.com",
  "synthios browser resize 1280 720",
  "synthios browser click 12 --double",
  'synthios browser type 23 "hello" --submit',
  "synthios browser press Enter",
  "synthios browser hover 44",
  "synthios browser drag 10 11",
  "synthios browser select 9 OptionA OptionB",
  "synthios browser upload /tmp/synthios/uploads/file.pdf",
  'synthios browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "synthios browser dialog --accept",
  'synthios browser wait --text "Done"',
  "synthios browser evaluate --fn '(el) => el.textContent' --ref 7",
  "synthios browser console --level error",
  "synthios browser pdf",
];
